### ISSUE TITLE
OutDec options

### ISSUE THREAD

**Issue by yurasmol** [xrobin/pROC#103]
pRoc does not react on options(OutDec=",") and use only dot delimiter for decimals

**Comment by xrobin** [comment]
It works for me.

```
> auc(roc(aSAH$outcome, aSAH$wfns, quiet=TRUE))
Area under the curve: 0.8237
> options(OutDec=",")
> auc(roc(aSAH$outcome, aSAH$wfns, quiet=TRUE))
Area under the curve: 0,8237

```

**Comment by yurasmol** [comment]
It does not work for plot(roc, print.thres="best", …) and legend()

От: Xavier Robin
Отправлено: 3 мая 2022 г. в 20:35
Кому: xrobin/pROC
Копия: yurasmol; Author
Тема: Re: [xrobin/pROC] OutDec options (Issue #103)

It works for me.
> auc(roc(aSAH$outcome, aSAH$wfns, quiet=TRUE))
Area under the curve: 0.8237
> options(OutDec=",")
> auc(roc(aSAH$outcome, aSAH$wfns, quiet=TRUE))
Area under the curve: 0,8237

**Comment by yurasmol** [comment]
Why you closed the non solved issue?

От: Xavier Robin
Отправлено: 3 мая 2022 г. в 20:35
Кому: xrobin/pROC
Копия: yurasmol; Author
Тема: Re: [xrobin/pROC] OutDec options (Issue #103)

Closed #103.

**Comment by yurasmol** [comment]
roc <- roc(aSAH$outcome, aSAH$wfns, quiet=T)
options(OutDec=",")
plot(roc, print.thres="best", print.auc=T)

От: Xavier Robin
Отправлено: 3 мая 2022 г. в 20:35
Кому: xrobin/pROC
Копия: yurasmol; Author
Тема: Re: [xrobin/pROC] OutDec options (Issue #103)

It works for me.
> auc(roc(aSAH$outcome, aSAH$wfns, quiet=TRUE))
Area under the curve: 0.8237
> options(OutDec=",")
> auc(roc(aSAH$outcome, aSAH$wfns, quiet=TRUE))
Area under the curve: 0,8237

**Comment by xrobin** [comment]
I see.

That's because `sprintf` doesn't seem to care about the OutDec option

    options(OutDec=",")
    sprintf("%.3f", 0.86771)
    # [1] "0.868"

That's something that would have to be fixed in base R, see [bug reporting in R](https://www.r-project.org/bugs.html)

In the meantime for your use case you can add the AUC to the plot separately:

    plot(roc, print.thres="best", print.auc=F)
    text(.5, .5, format(auc(roc), digits=3), adj=c(0,1))
