### ISSUE TITLE
not enough details in coord() "best" method

### ISSUE THREAD

**Issue by yuliaUU** [xrobin/pROC#105]
Hi, I wonder if you can provide additional details on "best " method in `coord()` function.
I am trying the following syntax where i specify "best" method:
`roc1.out <- coords(roc1, "best", ret = c("threshold", "sens", "spec"), transpose = TRUE)`

I am trying to find out which method is used here:
according to documentation: `if x="best", the method to determine the best threshold. See details in the ‘Best thresholds’ section.`
but in that section 2 methods are described: ``“youden”` and `“closest.topleft”`, but which one is used - I was not clear.
it looks like the default argument is set : `best.method=c("youden","closest.topleft")` - but how the optimal is obtained- I am not clear: from both methods you get a threshold - which one is picked ( what criteria is used to figure out whether youden or closest.topleft threshold is used) ?

**Comment by yuliaUU** [comment]
Yes! Just mentioning the default is sufficient!

**Comment by xrobin** [comment]
I added clarifications which are now on the master branch and will be available with the next release.
