### ISSUE TITLE
Averaging 10 ROC curves 

### ISSUE THREAD

**Issue by martinmargh** [xrobin/pROC#108]
Hi! I have computed 10 ROC values to test my model's performance (I'm working with GLMMs) with a 10-fold cross-validation. Because I need an averaged value of AUC, I stored my results in a list and saved as an rds file to compute the mean between those curves. 
I'm looking for a function or similar to compute the average ROC and AUC with a measure of error (e.g. confidence intervals as the ones provided by the roc or standard deviation estimates).

Thank you!

**Comment by xrobin** [comment]
Hi, thanks for the report!
Would that be covered by issue #41?

**Comment by martinmargh** [comment]
Hi! Yes, I'm exactly looking for a function that takes as input my roc values. Is it available for pROC?
Thank you!

**Comment by xrobin** [comment]
There's code in [ci.thresholds that does something like that](https://github.com/xrobin/pROC/blob/master/R/ci.thresholds.R#L107), but  it's not exposed in any way.

**Comment by martinmargh** [comment]
Ok, it seems perfect to compute ci for the averaged roc curve...but I can't find a way to compute this averaged curve.
