### ISSUE TITLE
How to print the threshold without specificity and sensitivity

### ISSUE THREAD

**Issue by DrLilei** [xrobin/pROC#109]
with the print.thres=T threshold, specificity and sensitivity could be print on the ROC curve. but how could I only print the threshold on the curve?

**Comment by xrobin** [comment]
There's the `print.thres.pattern` argument already...

    plot(rocobj, print.thres=TRUE, print.thres.pattern="%.3f")

Please let me know if that doesn't address your question.

**Comment by DrLilei** [comment]
The question has been addressed. Thanks.

李磊
13815434184
睡眠医学科
连云港市第四人民医院
(本邮件发送自手机)
________________________________
发件人: Xavier Robin ***@***.***>
发送时间: Sunday, January 22, 2023 12:05:59 AM
收件人: xrobin/pROC ***@***.***>
抄送: DrLilei ***@***.***>; Author ***@***.***>
主题: Re: [xrobin/pROC] How to print the threshold without specificity and sensitivity (Issue #109)


There's the print.thres.pattern argument already...

plot(rocobj, print.thres=TRUE, print.thres.pattern="%.3f")


Please let me know if that doesn't address your question.

―
