### ISSUE TITLE
Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.

### ISSUE THREAD

**Issue by MichaelChirico** [xrobin/pROC#117]
https://github.com/xrobin/pROC/blob/edcd42d7f63210e51830e69b5528d968235edf37/tests/testthat/test-ggroc.R#L7

This is throwing a warning in the testthat suite. The recommended alternative:

```
ℹ Please use `linewidth` instead.
```

**Comment by xrobin** [comment]
Support for the `linewidth` argument was added in c0569fc.
However the tests still have to be fixed.
Note: linewidth is not available in ggroc < 3.4.0 and tests should be skipped for older versions.
