### ISSUE TITLE
pROC, detectable AUC, more samples produce lower AUC value

### ISSUE THREAD

**Issue by WenjiangDeng** [xrobin/pROC#124]
Hi I was trying to calculate the detectable AUC by sample size using the power.roc.test(). It's a little confusing why a larger sample size produce smaller AUC values, cuz I would expect a higher AUC from more samples. Did I understand correctly? Thank you!

library(pROC)
> power.roc.test(ncases=20, ncontrols=20, sig.level=0.05, power=0.95)

     One ROC curve power calculation 

         ncases = 20
      ncontrols = 20
            auc = 0.8013171
      sig.level = 0.05
          power = 0.95

> power.roc.test(ncases=40, ncontrols=40, sig.level=0.05, power=0.95)
 
     One ROC curve power calculation 

         ncases = 40
      ncontrols = 40
            auc = 0.7210837
      sig.level = 0.05
          power = 0.95

**Comment by xrobin** [comment]
What numbers were you expecting exactly?

**Comment by xrobin** [comment]
The calculations look correct. I think you're being confused here: the `power.roc.test()` function does not calculate the maximum AUC that can be achieved, it is a power test to indicate what expected AUC could be significant (roughly speaking). Please refer to the function documentation and references for more details.

Feel free to reopen the issue if you still think anything is wrong with the function.

**Comment by WenjiangDeng** [comment]
That's right. Thanks!
