### ISSUE TITLE
plot(roc()) x not start from 0

### ISSUE THREAD

**Issue by littlecabiria** [xrobin/pROC#132]
Hi Team, 

I tried to use the package and follow the example:
library(pROC)
data(aSAH)
roc(outcome ~ s100b, aSAH)
plot(roc(outcome ~ s100b, aSAH))

However, the graph looks like this
<img width="864" alt="Screenshot 2024-12-01 at 12 42 09" src="https://github.com/user-attachments/assets/3015b8d6-ff89-4fde-8e5a-cdbf41306e8d">

is it possible that the x starts from 0?

**Comment by xrobin** [comment]
There are [several answers on how to rescale the axis on StackOverflow](https://stackoverflow.com/q/42057979).
