### ISSUE TITLE
ggroc x-axis

### ISSUE THREAD

**Issue by adatum** [xrobin/pROC#21]
Is there an easy way to have `ggroc` plot the false positive rate (1 - specificity) on the x-axis? 

By default `ggroc` plots specificity on the reversed x-axis over [1, 0], instead of the perhaps more familiar (1-specificity) over [0, 1].

**Comment by xrobin** [comment]
This is not trivial at the moment, as you'd need to replace the data and aesthetics before changing the axis. I will consider adding an equivalent to `legacy.axis` in a future version.

**Comment by xrobin** [comment]
I added a `legacy.axes` argument to ggroc in commit baed9bee6af4eff460c5b7b5a1c5f42e005c3508. You can test it in the latest master version from github:

    devtools::install_github("xrobin/pROC")
    ...
    ggroc(rocobj, legacy.axes = TRUE)

**Comment by adatum** [comment]
That works perfectly. Thanks for the quick edits!
