### ISSUE TITLE
Question: Specify (hardcode) negative outcome in advance

### ISSUE THREAD

**Issue by Tazinho** [xrobin/pROC#23]
I want to calculate the AUC for many subgroups, one at a time (in a foreach loop).
From my understanding the `direction` can change every time depending on the relation of 0 vs. 1 in the outcome, so I don't see if the AUC would be under 0.5.

Is it possible to specify the "negative outcome" or the "positive outcome" in advance?
I am currently using a workaround like 
```
direction_i <- if(mean(df_i[["outcome"]]) < 0.5) {">"} else {"<"}
```
in every step, which is ok for my use case.

However, in general I would find your package much more appealing, if this could be specified directly.
Am I missing sth. obvious?

**Comment by xrobin** [comment]
Use the `levels` argument. See in `?roc` where you'll find the following example:

     roc(aSAH$outcome, aSAH$s100b,
         levels=c("Poor", "Good"), direction="<")

**Comment by Tazinho** [comment]
Nice, I didn't thaught of the combination of these arguments.
Thanks!
