### ISSUE TITLE
Generalized AUC for more than 2 outcome categories

### ISSUE THREAD

**Issue by f-roche** [xrobin/pROC#55]
I'd like to compute the Generalized AUC for comparing methods that should separate 3 different categories (e.g. no, mild, severe disease).
https://stats.stackexchange.com/questions/112383/roc-for-more-than-2-outcome-categories

Does your package provide that kind of statistic?

Thanks

**Comment by xrobin** [comment]
pROC has a [multiclass.roc](https://rdrr.io/cran/pROC/man/multiclass.html) function. If you have anything else in mind please feel free to re-open the issue.
