### ISSUE TITLE
ggroc disregards order

### ISSUE THREAD

**Issue by DSLituiev** [xrobin/pROC#58]
When plotting with `ggroc`, the curves appear in alphabetic order, and not in the order they are present in the named list.

**Comment by xrobin** [comment]
Thanks for the patch. I fixed the visual tests, which were re-ordered of course. Some AppVeyor tests in Windows are still failing and I need to investigate why, but apparently unrelated with this change.

As it is a bug fix more than a new feature I will target to release a minor 1.15.1 shortly.
