### ISSUE TITLE
Checking AUC CI

### ISSUE THREAD

**Issue by privefl** [xrobin/pROC#61]
**Describe the bug**
Checking a function implemented in my package {bigstatsr} with the one implemented in {pROC}, I don't get the same results.

**To Reproduce**
```
set.seed(1)
x <- runif(100)
y <- sample(0:1, size = length(x), replace = TRUE)
pROC::ci.auc(y, x, method = "bootstrap", boot.n = 10e3)  # 0.4291-0.655
bigstatsr::AUCBoot(x, y)  # 0.3447-0.571
```
Am I using it wrong?

**Comment by xrobin** [comment]
I am fairly positive about the values given by pROC's bootstrap test, if only because they asymptotically approximate those of the DeLong test:

```
pROC::ci.auc(y, x, method = "delong")
Setting levels: control = 0, case = 1
Setting direction: controls > cases
95% CI: 0.4286-0.6575 (DeLong)
```

I assume your package must process the data differently, as your values are close to 1-pROC's CI.

**Comment by privefl** [comment]
If I look at
```
> by(x, y, mean)
y: 0
[1] 0.538855
------------------------------------------------------------- 
y: 1
[1] 0.4999514
```
the values of `x` for `y = 0` are larger (in mean) than for `y = 1` so I expect an AUC lower than 0.5 (what I get -> 0.457). And I expect the CI to be somewhat centered around this value.

**Comment by xrobin** [comment]
That behavior is controlled by the `levels` and `direction` arguments.

**Comment by privefl** [comment]
If I try with `y <- ordered(sample(0:1, size = length(x), replace = TRUE))`, I get the same result.

**Comment by xrobin** [comment]
I don't see the relevance of your last comment to this discussion. Please read the manual at `?ci.auc` and `?roc`.

**Comment by privefl** [comment]
I did read the documentation of `?ci.auc` and did not see any reference to `levels` or `direction`.
I thought you were talking about factors.
