### ISSUE TITLE
Manual needs to have cross-reference

### ISSUE THREAD

**Issue by kingcrimsontianyu** [xrobin/pROC#66]
Would be much better if the manual has cross-references, allowing readers to quickly navigate to referenced pages/functions/sections with a mouse click.

**Comment by xrobin** [comment]
The manual has plenty of cross-references. See
https://www.rdocumentation.org/packages/pROC/versions/1.14.0/topics/roc
https://www.rdocumentation.org/packages/pROC/versions/1.14.0/topics/pROC-package
Can you be more specific with what you'd like cross-referenced exactly?

**Comment by kingcrimsontianyu** [comment]
Dear Xavier, thanks for your reply!
I was referring to the PDF manual: https://cran.r-project.org/web/packages/pROC/pROC.pdf
It would be great if cross-reference works like this: https://cran.r-project.org/web/packages/randomForest/randomForest.pdf

**Comment by xrobin** [comment]
Oh this is weird. It looks like an issue with the CRAN-generated pdf. If I [generate it myself with R CMD Rd2pdf](https://github.com/xrobin/pROC/files/3881705/pROC.pdf) the cross-links are there. This was probably a temporary issue on CRAN at the time of upload. Nothing I can do about except checking what happens with the next release.

**Comment by kingcrimsontianyu** [comment]
Thanks!
