### ISSUE TITLE
Exporting AUC values from pROC 

### ISSUE THREAD

**Issue by GabPoll** [xrobin/pROC#7]
Hello, I've been using pROC in last few days. Very nice and works well for getting AUC out. However, I can't seem to find a way to extract AUC values out into txt or csv files. I was hoping to loop through several columns of an input datafile in order to calculate the AUC for each variable.

Many thanks for your help

**Comment by xrobin** [comment]
Have you looked at the `auc` function? What you do with the results (print, write to file, etc) is entirely up to you from there.

**Comment by GabPoll** [comment]
thank you @xrobin . Sorted it now. Cheers G
