### ISSUE TITLE
choose my own auc0

### ISSUE THREAD

**Issue by coralzhang** [xrobin/pROC#71]
It seems that your function power.roc.test tests/powers for the null of auc0=0.5, I wonder if there could be a quick workaround to let me choose my own auc0, say I want to have auc0=0.6, and calculate sample size for an alternative of auc1=0.7. 

Thank you very much!

**Comment by xrobin** [comment]
I am closing this issue as it is unclear what needs to be done exactly, and is not a priority right now.

For the record the discussion happened separately over email. Here is the main answer:

> Obuchowski et al., 2004 describe how to perform the one ROC curve sample size test in eq. 2. They don't show the whole derivation in the paper though, and I doubt the 0.5 can be substituted with an arbitrary auc0.
> 
> Alternatively if you want to compare your curve to a hypothetical, known but not the null AUC, you have several options for a two ROC curves test, depending on  what you know about the curves and the data.
> 
> Probably the easiest is to use the parslist argument, see ?power.roc.test and Obuchowski and McClish (1997). You will need the binormal parameters of the two curves and the correlation between the variables in negative and positive patients.
> 
> Alternatively, you can use a modified version of the test with two ROC curves. As Markus mentioned you need to calculate the variance of the curve. Fortunately Obuchowski and McClish (1997) describe a method to estimate it without data, under the binormal assumption. This method is used internally in pROC already.
> 
> Most of the code should already exist and you should be able to get started by looking at the source code in power.roc.test.R, cov.R and obuchowski.R.
