### ISSUE TITLE
Please remove Rcpp 1.0.3 test

### ISSUE THREAD

**Issue by eddelbuettel** [xrobin/pROC#75]
### Describe the bug

pROC blocks Rcpp reverse dependency checking via a (now spurious) check

### Details 

Running R CMD check on the current Rcpp release candidate (post 1.0.4 release) gets us

```
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 8641 | SKIPPED: 24 | WARNINGS: 73 | FAILED: 1 ]
  1. Failure: We're running the right Rcpp version (@test-onload.R#48) 
```

I forget why that was ever needed.  What was the issue?  Why did we decide to fix a symptom and not a cause?

**Comment by xrobin** [comment]
This test is supposed to run only on CI. I think that this restriction was removed by accident with Rcpp 1.0.3. I'm preparing a release which I'll push to CRAN asap.

**Comment by eddelbuettel** [comment]
I bit me when reverse-depends checking so it must have leaked out.  Appreciate the prompt reply!

**Comment by xrobin** [comment]
I hate it when reverse dependency checks fail. I don't have as many as you do so I can feel your pain.

I submitted pROC 1.16.2 to CRAN just now, hopefully it will go through quickly.

**Comment by eddelbuettel** [comment]
And it's already in!  https://twitter.com/CRANberriesFeed/status/1240700177930792960
