### ISSUE TITLE
coords error

### ISSUE THREAD

**Issue by mbalcerzyk** [xrobin/pROC#79]
Hi.
 
If you run example from the page https://rdrr.io/cran/pROC/man/coords.html in the browser, it ends in an error after few outputs

 > Error in cc$sensitivity : $ operator is invalid for atomic vectors
>Calls: print Execution halted
 
I wanted to see Youden calculated.
 
Could you fix it? I hope that page was quite official pROC site...
 
Kind regards
 
Marcin Balcerzyk, 
Universidad de Sevilla

**Comment by xrobin** [comment]
Hi Marcin, thank you for the report.

Unfortunately rdrr.io seems to be running an outdated version of pROC, which is not in sync with the help page:

    > print(packageVersion("pROC"))
    [1] '1.14.0'

It has been replaced by 1.15.0 more than a year ago already. The latest version (1.16.2) is available on CRAN https://cran.r-project.org/web/packages/pROC/
Please use this version instead to run the examples.
