### ISSUE TITLE
ggroc on smooth.roc objects

### ISSUE THREAD

**Issue by arubio2** [xrobin/pROC#86]
It would be great if ggroc could work also on smooth.roc objects.
By the way, good and nice work.

**Comment by xrobin** [comment]
This should be doable rather easily.

**Comment by xrobin** [comment]
This feature is now available for testing on the master branch.

**Comment by xrobin** [comment]
The feature has been merged into pROC 1.17.0 which is ready for release on CRAN (see #89).
