### ISSUE TITLE
Value of AUC and ROC curve

### ISSUE THREAD

**Issue by 814471489** [xrobin/pROC#94]
**Describe the bug**
The axis of the ROC curve should be 1-specificity. And this figure is wrong, is the value of AUC correct? 

**Additional context**
![90004A04-5B7E-444F-A049-0CC192BAB991](https://user-images.githubusercontent.com/49757159/116379918-10ebd480-a846-11eb-8216-d57e77084265.png)

**Comment by xrobin** [comment]
No it should not, and no the figure is correct. See the first question in the FAQ:  https://github.com/xrobin/pROC/wiki/FAQ---Frequently-asked-questions#the-x-axis-should-be-1-specificity-instead-of-specificity
